<?php

namespace PostBundle\Repository;
use Doctrine\ORM\EntityRepository;
use PostBundle\Entity\Post;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function findLastPosts( $page = 1, $limit = 10 ){
        $query = $this->createQueryBuilder('p');
        $query->setMaxResults($limit);
        $query->setFirstResult( ($limit * $page) - $limit );
        $query->orderBy('p.id', 'DESC');
        return $query->getQuery()->getResult();
    }

    public function countPage(){
        $query = $this->createQueryBuilder('p')->select('count(p.id)');
        $result = $query->getQuery()->getOneOrNullResult();
        return $result ? array_shift($result) : 0;
    }
}
